### ISSUE TITLE
No release for MacOS ARM64

### ISSUE THREAD

**Issue by caleb-acosta** [burrito-elixir/erlang-builder#2]
I found that there is no release for any version of OTP 25 for darwin arm64, it would be super nice if you can add it.

**Comment by doawoo** [comment]
you're right! I'll kick off a build for OTP-25 versions right away!

**Comment by hochata** [comment]
Hi @doawoo!

The last build failed... Do you think you could take a look?

**Comment by hochata** [comment]
It seems the `CXX` for cross compilation wasn't defined. Not sure how it worked before, but setting it fixed the build (or at lease I hope).

I'm still testing to see if something doesn't work. If everything goes right I'll make a PR later today. 

I've been doing test [here](https://github.com/hochata/burrito_builder), because Github Actions doesn't like running on forks...

**Comment by hochata** [comment]
Hey @doawoo, do you think you could trigger a new release? The one from yesterday doesn't include yet a Mac Silicon release for OTP 25 :sweat_smile:

**Comment by doawoo** [comment]
> Hey @doawoo, do you think you could trigger a new release? The one from yesterday doesn't include yet a Mac Silicon release for OTP 25 😅

Sure! can do. 
FYI We'll be moving to a new Erlang builder CI soon :)

**Comment by hochata** [comment]
Nice! Any news about when it will be ready?

**Comment by doawoo** [comment]
> Nice! Any news about when it will be ready?

I'm currently still doing some testing, but, you can actually try it out by setting your local `:burrito` dependency declaration in your `mix.exs` to use branch `digit/beam-machine-download`.
